### ISSUE TITLE
SqlWatchImport.exe sometimes fails with null task or index out of bounds

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#306]
Thanks for your feedback Marcin!

I use a sql server as concentrator of 4 sqlserver using login/password to connect.
my version is Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
SQLWATCH 3.0.9.18505
SQLWATCH Remote Instance Importer 1.1.7757.27362

The job is always running when the command is not with > NUL.
This is one message for example
Date		21/04/2021 14:50:00
Log		Job History (SQLWATCH-EXTERNAL-IMPORT)

Step ID		1
Server		SERVERNAME
Job Name		SQLWATCH-EXTERNAL-IMPORT
Step Name		SqlWatchImport.exe
Duration		00:31:20
Sql Severity	0
Sql Message ID	0
Operator Emailed	
Operator Net sent	
Operator Paged	
Retries Attempted	0

Message
nnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at SqlWatchImport.SqlWatchInstance.<>c__DisplayClass47_1.<ImportAsync>b__3(SqlWatchTable Table)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at SqlWatchImport.SqlWatchInstance.<>c__DisplayClass47_1.<ImportAsync>b__3(SqlWatchTable Table)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #3) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at SqlWatchImport.SqlWatchInstance.<>c__DisplayClass47_1.<ImportAsync>b__3(SqlWatchTable Table)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #4) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at SqlWatchImport.SqlWatchInstance.<>c__DisplayClass47_1.<ImportAsync>b__3(SqlWatchTable Table)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

---> (Inner Exception #7) System.ArgumentException: The tasks argument included a null value.
Parameter name: tasks
   at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1 tasks)
   at SqlWatchImport.SqlWatchInstance.<>c__DisplayClass47_0.<ImportAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SqlWatchImport.SqlWatchInstance.<ImportAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SqlWatchImport.Program.<>c__DisplayClass0_2.<<Main>b__2>d.MoveNext()<---
 (Thread: 1)

_Originally posted by @LionelFremondiere in https://github.com/marcingminski/sqlwatch/issues/263#issuecomment-824060298_

**Comment by marcingminski** [comment]
I am able to replicate this, but it looks like it is a timing issue. I am still working on the fix.

**Comment by marcingminski** [comment]
I found it. testing it now and will publish a fix soon.

**Comment by marcingminski** [comment]
```
Unhandled Exception: System.ArgumentException: The tasks argument included a null value.
Parameter name: tasks
   at System.Threading.Tasks.Task.WhenAll(Task[] tasks)
   at SqlWatchImport.Program.Main(String[] args) in C:\Users\marcin\Documents\GitHub\sqlwatch\sqlwatch\SqlWatch.Monitor\Project.SqlWatchImport\Program.cs:line 157
```

**Comment by marcingminski** [comment]
I believe the reason the application was never closing is because the error was not handled and it was simply crashing with a message box waiting for the user input

**Comment by marcingminski** [comment]
@LionelFremondiere can you try the latest version of the SqlWatchImporter.exe please?
