### ISSUE TITLE
Unhandled Exception -> System indexOutOfRangeException every now and then

### ISSUE THREAD

**Issue by pluim003** [marcingminski/sqlwatch#438]
**Describe the bug**
Every now and then the SQL-IMPORTER-job fails, although (most of) the data has been captured. Errormessage:

Date		8-2-2022 09:05:00
Log		Job History (SQLWATCH-IMPORTER)

Step ID		1
Server		WPZKH1879
Job Name		SQLWATCH-IMPORTER
Step Name		SQLWatch - import
Duration		00:00:01
Sql Severity	0
Sql Message ID	0
Operator Emailed	
Operator Net sent	
Operator Paged	
Retries Attempted	0

Message
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at SqlWatchImport.Program.<>c__DisplayClass0_2.<Main>b__0(RemoteInstance RemoteInstance) in C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatchImport\Program.cs:line 154
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SqlWatchImport.Program.Main(String[] args) in C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatchImport\Program.cs:line 125

Unclear which of the 30 instances to be monitored throws this...

**To Reproduce**
Happens randomly. Next run as it runs every 5 minutes might succeed without errors and then after a while the same error occurs.

**Expected behavior**
No error

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: Windows 2016

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2017
 - SQL Edition: Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 4.3.0.x
 
**Additional context**

**Comment by marcingminski** [comment]
Hi, is this still an issue or has it been fixed since you raised the bug?

**Comment by pluim003** [comment]
Well, it's been almost 8 months since I logged the issue. About 6 months or so we switched from Sqlwatch to Zabbix. So unfortunately we don't use sqlwatch anymore and I can't tell if the same problem still is present.

**Comment by marcingminski** [comment]
Zabbix is good! I used to use it extensively and will be happy to help you with SQL templates (if you need any help!)

**Comment by pluim003** [comment]
Thanx @marcingminski , always handy, to compare with ours at the company.
